- hosts: all
  become: true
  roles:
    - base

- hosts: nfs_servers
  become: true
  roles:
    - nfs_servers

- hosts: nfs_clients
  become: true
  roles:
    - nfs_clients 

- hosts: vsftp_servers
  become: true
  roles:
    - vsftp
  tags: vsftp


- hosts: vsftp_clients
  become: true
  roles:
    - vsftp_clients
  tags: vsftp

