- hosts: all
  become: true
  roles:
    - base

- hosts: nfs_servers
  become: true
  roles:
    - nfs_servers

- hosts: nfs_clients
  become: true
  roles:
    - nfs_clients 

- hosts: vsftp_servers
  become: true
  roles:
    - vsftp_servers
  tags: vsftp

- hosts: vsftp_clients
  become: true
  roles:
    - vsftp_clients
  tags: vsftp

- hosts: web_servers
  become: true
  roles:
    - web_servers
  tags: httpd

- hosts: db_servers
  become: true
  roles:
    - db_servers
  tags: db_servers


- hosts: mariadb_servers
  become: true
  roles:
    - mariadb_servers
  tags: mariadb_servers

