- hosts: all
  become: true
  roles:
    - base

- hosts: centos9-app
  become: true
  roles:
    - useradd
  tags: useradd

- hosts: app_servers
  become: true
  roles:
    - app_servers

- hosts: nfs_servers
  become: true
  roles:
    - nfs_servers

- hosts: nfs_clients
  become: true
  roles:
    - nfs_clients 

- hosts: vsftp_servers
  become: true
  roles:
    - vsftp_servers
  tags: vsftp

- hosts: vsftp_clients
  become: true
  roles:
    - vsftp_clients
  tags: vsftp

- hosts: web_servers
  become: true
  roles:
    - web_servers
  tags: httpd

- hosts: db_servers
  become: true
  roles:
    - db_servers
  tags: db_servers


- hosts: mariadb_servers
  become: true
  roles:
    - mariadb_servers
  tags: mariadb_servers

- hosts: nginx_web_servers
  become: true
  roles:
    - nginx_web_servers
  tags: nginx_web_servers

