---

# target host or group
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Refer to Gathering Facts
      command: echo "{{ ansible_distribution }} "
      register: dist

    - debug: msg="{{ dist.stdout }}"

    - name: Test Task
      file:
        path: /home/fidel/ansible_test.txt
        state: absent
        owner: fidel
        group: fidel
        mode: 0600
 

    - name: cat a file on target hosts  
      tags: apache, httpd, centos
      command: cat /var/www/html/index.html
      register: cat_output
      when: ansible_distribution == "CentOS"

- name: Install Vsftp server
  hosts: nfs_servers
  become: true
  become_user: root
  tasks:
    - name: Install Vsftp server
      package:
        name: vsftpd
        state: present
      when: ansible_distribution == "CentOS"
      tags: vsftp,centos 




