---

# target host or group
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Refer to Gathering Facts
      command: echo "{{ ansible_distribution }} "
      register: dist

    - debug: msg="{{ dist.stdout }}"

    - name: Test Task
      file:
        path: /home/fidel/ansible_test.txt
        state: absent
        owner: fidel
        group: fidel
        mode: 0600
 
    - name: Edit file with multiple lines added  
  #    hosts: alma9
      blockinfile:
        path: /tmp/fidel.txt
        block: |
          This is the first line to add
          This is the second line to add
          This is the third line to add
        
