---

# target host or group
- hosts: all
  become: true
  become_user: root
  tasks:
     - name: Refer to Gathering Facts
       command: echo "{{ ansible_distribution }} {{ ansible_distribution_version }} "
       register: disti

     - debug: msg="{{ dist.stdout }}"

    - name: Test Task
      file:
        path: /home/fidel/ansible_test.txt
        state: absent
        owner: fidel
        group: fidel
        mode: 0600
 
    - name: Refer to Gathering Facts
      command: echo "{{ ansible_distribution }} {{ ansible_distribution_version }} "
      register: dist
    - debug: msg="{{ dist.stdout }}"


   - name: cat a file on target hosts  
     tags: apache, httpd, centos
     command: cat /var/www/html/index.html
     register: cat_output
     when: ansible_distribution == "CentOS"
