---

# target host or group
- hosts: name_nodes
  become: true
  become_user: root
  tasks:
  
  - name: Refer to Gathering Facts
    command: echo "{{ ansible_distribution }}"
    register: dist

  - debug: msg="{{ dist.stdout }}"  

  - name: Install Updates (CentOS) 
    tags: CentOS
    dnf:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "CentOS"
        
  - name: Install Updates (Ubuntu)
    tags: Ubuntu
    apt:
       upgrade: dist
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure General Packages are installed
    tags: always
    package:
      name: 
       - tar
       - wget
       - unzip
      state: present
