- name: Install mariadb-server
  ansible.builtin.package:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: present

- name: Create new charaset
  file: 
    path: /etc/my.cnf.d/charset.cnf
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Copy content from charaset_default to charset.cnf
  copy:
    src: files/charaset_default.txt
    dest: /etc/my.cnf.d/charset.cnf

- name: Start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Add database zone to firewall
  firewalld:
    zone: database
    permanent: yes
    state: present

- name: Enable database querry sources
  firewalld:
    source: 192.168.122.0/24
    zone: database
    permanent: yes
    state: enabled

- name: open firewall ports
  firewalld:
    zone: database
    port: 3306/tcp
    permanent: yes
    state: enabled

