- name: Update Centos/RedHat packages
  import_tasks: update_package.yml

- name: Install basic packages
  package:
     name: "{{ item }}"
     state: present
  with_items: "{{ packages }}"

- name: Add firewall service 
  include_tasks: add_service_firewall.yml
  vars:
    firewall_name: "{{ item }}"
  loop: 
   - ntp
  when: ansible_os_family == "RedHat"

- name: Start "{{ item }}" service
  include_tasks: start_service.yml
  vars:
    service_name: "{{ item }}"
  loop:
    - chronyd
    

