
- name: Update packages on CentOS/RHEL
  yum:
    name: '*'  # Update all packages
    state: latest  # Ensure they are up to date
  when: ansible_os_family == "RedHat"

- name: Install ntpdate
  package:
    name: chrony
    state: present
  tags: ntp,chronyd    

- name: Start chronyd
  service:
    name: chronyd
    state: started 
    enabled: yes
  tags: chronyd,ntp

- name: Add chronyd service to firewall
  firewalld:  
    service: ntp
    permanent: yes    # Make the change permanent
    state: enabled    # Enable the NFS service in the firewall
  when: ansible_os_family == "RedHat"
  tags: chronyd-firewalld

- name: Reload firewalld to apply changes
  firewalld:
    state: enabled
  when: ansible_os_family == "RedHat"
  tags: chronyd-firewalld

- name: Ensure General Packages are installed
  tags: always
  package:
      name: 
        - tar
        - wget
        - unzip
        - curl
        - vim
      state: present

