---
# tasks file for ssh_config
- name: update SSH configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'ssh -t -f %s'
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port 22"
  notify: restart "{{ service_name }}"
  
- name: Add ssh key for user "{{ username  }}"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{  lookup('file', lookup('env','HOME') + '/.ssh/ansible.pub') }}"
  tags: ssh_key
 
- name: Start "{{ service_name }}"
  service:
    name: "{{ service_name }}"
    state: started 
    enabled: yes
  tags: "{{ service_name }}"  
